env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'import'
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/no-extraneous-dependencies:
    - error
ignorePatterns:
  - '**/dist'
  - '**/build'
  - '**/*.js'
  - '**/node_modules'
